In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
netflix_df = pd.read_csv("netflix_data.csv")

In [3]:
#To view the first 5 data rows
netflix_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas

In [4]:
#To get the names of the columns in the dataset
netflix_df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'duration', 'description', 'genre'],
      dtype='object')

In [5]:
#to determine the types of data in the dataframe per column.
netflix_df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
duration         int64
description     object
genre           object
dtype: object

In [6]:
#To get tv shows released from 2018 in Brazil
tv_shows_brazil = netflix_df[(netflix_df["country"] == 'Brazil')& (netflix_df["release_year"] > 2018) & (netflix_df["type"] == "TV Show")]

In [7]:
tv_shows_brazil.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV
218,s219,TV Show,A Queen Is Born,Carla Barros,"Gloria Groove, Alexia Twister",Brazil,"November 11, 2020",2020,1,Gloria Groove and Alexia Twister make drag dre...,International TV
531,s532,TV Show,Anitta: Made In Honório,"Andrucha Waddington, Pedro Waddington",Anitta,Brazil,"December 16, 2020",2020,1,"In this intimate documentary, Brazilian pop qu...",Docuseries
1115,s1116,TV Show,Brotherhood,NaN,"Naruna Costa, Seu Jorge, Hermila Guedes, Lee T...",Brazil,"October 25, 2019",2019,1,An honest lawyer reaches a moral crossroads af...,Crime TV
1626,s1627,TV Show,Dating Around: Brazil,Cassia Dian,NaN,Brazil,"July 10, 2020",2020,1,"In this reality show, six singles meet five di...",International TV

In [8]:
#Remove tv shows from the dataframe.
netflix_subset = netflix_df[netflix_df["type"] != "TV Show"]

In [9]:
netflix_subset.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas
6,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,95,"After an awful accident, a couple admitted to ...",Horror Movies

In [10]:
#To see unique values in the type column
netflix_df["type"].nunique()

2

In [11]:
#keep "title", "country", "genre", "release_year", "duration", and saving this into a new DataFrame called netflix_movies.
netflix_movies = netflix_df[["title", "country", "genre", "release_year", "duration"]]

In [12]:
netflix_movies.head()

   title        country             genre  release_year  duration
0     3%         Brazil  International TV          2020         4
1   7:19         Mexico            Dramas          2016        93
2  23:59      Singapore     Horror Movies          2011        78
3      9  United States            Action          2009        80
4     21  United States            Dramas          2008       123

In [13]:
#netflix_movies shorter than 60 minutes
short_movies = netflix_df[netflix_df["duration"] < 60]

In [14]:
short_movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV
5,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,1,A genetics professor experiments with a treatm...,International TV
11,s12,TV Show,1983,NaN,"Robert Więckiewicz, Maciej Musiał, Michalina O...",Poland,"November 30, 2018",2018,1,"In this dark alt-history thriller, a naïve law...",Crime TV
12,s13,TV Show,1994,Diego Enrique Osorno,NaN,Mexico,"May 17, 2019",2019,1,Archival video and new interviews examine Mexi...,Crime TV
16,s17,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,1,"As a psychology professor faces Alzheimer's, h...",International TV

In [15]:
#loop through the dataset, and add different genres as colors in a list.
colors = []
for lab, row in netflix_movies.iterrows():
    if row['genre'] == 'Children':
        colors.append("Red")
    elif row['genre'] == 'Documentaries':
        colors.append('Blue')
    elif row['genre'] == 'Stand-Up':
        colors.append('Yellow')
    else:
        colors.append('Black')